# Generated by Django 4.2.3 on 2023-07-27 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="image",
        ),
        migrations.AddField(
            model_name="products",
            name="images",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.images",
                verbose_name="Изображение товара",
            ),
        ),
    ]
