# Generated by Django 4.2.3 on 2023-07-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0002_remove_products_image_products_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="images",
            field=models.ImageField(
                blank=True,
                default="G:\\RealShit / images/bigGoods.png",
                null=True,
                upload_to="G:\\RealShit / images/",
                verbose_name="Изображение товара",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Название товара"
            ),
        ),
        migrations.DeleteModel(
            name="Images",
        ),
    ]
